TiendaSaludable/TiendaSaludable/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from productos.views import home, registro, lista_articulos, carrito, contacto, agregar_al_carrito, eliminar_del_carrito

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('productos.urls')),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('registro/', registro, name='register'),
    path('home/', home, name='home'),
]

TiendaSaludable/productos/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import home, lista_articulos, carrito, contacto, agregar_al_carrito, eliminar_del_carrito, RegistroUsuario

app_name = 'productos'

urlpatterns = [
    path('articulos/', lista_articulos, name='lista_articulos'),
    path('carrito/', carrito, name='carrito'),
    path('contacto/', contacto, name='contacto'),
    path('', home, name='home'),
    path('agregar_al_carrito/<int:producto_id>/', agregar_al_carrito, name='agregar_al_carrito'),
    path('carrito/eliminar/<int:item_id>/', eliminar_del_carrito, name='eliminar_del_carrito'),
    path('login/', auth_views.LoginView.as_view(template_name='productos/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='productos:home'), name='logout', kwargs={'next_page': 'productos:home'}),
    path('registro/', RegistroUsuario.as_view(), name='registro'),
]

TiendaSaludable/productos/models.py
from django.db import models

# Modelo para la categoría de productos
class Categoria(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre

# Modelo para los productos
class Producto(models.Model):
    nombre = models.CharField(max_length=200)
    descripcion = models.TextField()
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE, default=1)
    disponible = models.BooleanField(default=True)
    
    def __str__(self):
        return self.nombre

# Modelo para los clientes
class Cliente(models.Model):
    nombre = models.CharField(max_length=200)
    email = models.EmailField()

    def __str__(self):
        return self.nombre

# Modelo para los carritos de compra
class Carrito(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE, related_name='carritos')
    productos = models.ManyToManyField(Producto, through='ItemCarrito')

    def __str__(self):
        return f"Carrito de {self.cliente.nombre}"

# Modelo para los ítems en el carrito de compra
class ItemCarrito(models.Model):
    cliente = models.ForeignKey('Cliente', on_delete=models.CASCADE, related_name='carrito', default=None)
    producto = models.ForeignKey('Producto', on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField(default=1)

    def subtotal(self):
        return self.producto.precio * self.cantidad

    carrito = models.ForeignKey('Carrito', on_delete=models.CASCADE)

TiendaSaludable/productos/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Producto, Cliente, ItemCarrito

# Formulario para crear/editar un producto
class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = ['nombre', 'descripcion', 'precio', 'disponible', 'categoria']

# Formulario para crear/editar un cliente
class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ['nombre', 'email']

# Formulario de búsqueda
class BuscarForm(forms.Form):
    busqueda = forms.CharField(label='Buscar')

# Formulario para agregar un producto al carrito
class CarritoForm(forms.Form):
    producto_id = forms.IntegerField()
    cantidad = forms.IntegerField(min_value=1)

# Formulario para crear/editar un ítem en el carrito
class ItemCarritoForm(forms.ModelForm):
    class Meta:
        model = ItemCarrito
        fields = ['producto', 'cantidad']

# Formulario de contacto
class ContactoForm(forms.Form):
    nombre = forms.CharField(label='Nombre', max_length=100)
    apellido = forms.CharField(label='Apellido', max_length=100)
    email = forms.EmailField(label='E-mail')

    # Opciones para el motivo del contacto
    opciones_motivo = [
        ('consultas', 'Consultas'),
        ('reclamos', 'Reclamos'),
        ('promociones', 'Recibir Promociones'),
    ]

    motivo = forms.ChoiceField(label='Motivo', choices=opciones_motivo)
    comentarios = forms.CharField(label='Comentarios', widget=forms.Textarea)

# Formulario de registro de usuario
class RegistroUsuarioForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True, help_text='Nombre')
    last_name = forms.CharField(max_length=30, required=True, help_text='Apellido')
    email = forms.EmailField(required=True, help_text='Email')
    telefono = forms.CharField(max_length=15, required=False, help_text='Teléfono')
    avatar = forms.ImageField(required=False, help_text='Foto de perfil')

    class Meta:
        model = User
        fields = UserCreationForm.Meta.fields + ('first_name', 'last_name', 'email', 'telefono', 'avatar',)

TiendaSaludable/productos/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
from .models import Producto, Cliente, ItemCarrito
from .forms import BuscarForm, CarritoForm, ContactoForm, RegistroUsuarioForm

# Vista para la página principal
def home(request):
    return render(request, 'productos/home.html')

# Vista para el registro de usuario
def registro(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, '¡Bienvenido! Te has registrado exitosamente.')
            return redirect('productos:home')
    else:
        form = UserCreationForm()

    return render(request, 'productos/registro.html', {'form': form})

# Vista para la lista de artículos disponibles
def lista_articulos(request):
    # Filtra los productos disponibles y ordénalos por nombre
    articulos = Producto.objects.filter(disponible=True).order_by('nombre')
    return render(request, 'productos/lista_articulos.html', {'articulos': articulos})

# Vista para el carrito de compras
@login_required
def carrito(request):
    cliente = get_object_or_404(Cliente, id=request.user.id)
    carrito = cliente.carrito.all()
    total_carrito = sum(item.subtotal() for item in carrito)

    contexto = {'carrito': carrito, 'total_carrito': total_carrito}
    return render(request, 'productos/carrito.html', contexto)

# Vista para la página de contacto
def contacto(request):
    if request.method == 'POST':
        form = ContactoForm(request.POST)
        if form.is_valid():
            # Procesa los datos del formulario si es válido
            nombre = form.cleaned_data['nombre']
            apellido = form.cleaned_data['apellido']
            email = form.cleaned_data['email']
            motivo = form.cleaned_data['motivo']
            comentarios = form.cleaned_data['comentarios']
            # Aquí podrías realizar acciones adicionales con los datos del formulario

    else:
        form = ContactoForm()

    contexto = {'form': form}
    return render(request, 'productos/contacto.html', contexto)

# Vista para agregar un producto al carrito
def agregar_al_carrito(request, producto_id):
    producto = get_object_or_404(Producto, pk=producto_id, disponible=True)

    if request.user.is_authenticated:
        cliente, creado = Cliente.objects.get_or_create(email=request.user.email)
        item_carrito, creado = ItemCarrito.objects.get_or_create(producto=producto, cliente=cliente)
        item_carrito.cantidad += 1
        item_carrito.save()

    # Utiliza reverse para obtener la URL de 'productos:lista_articulos'
    lista_articulos_url = reverse('productos:lista_articulos')
    return redirect(lista_articulos_url)

# Vista para eliminar un ítem del carrito
def eliminar_del_carrito(request, item_id):
    item = get_object_or_404(ItemCarrito, id=item_id)
    item.delete()
    return redirect('productos:carrito')

# Vista para el registro de usuario
class RegistroUsuario(CreateView):
    form_class = RegistroUsuarioForm
    template_name = 'productos/registro.html'
    success_url = reverse_lazy('productos:home')

    def form_valid(self, form):
        response = super().form_valid(form)
        login(self.request, self.object)
        messages.success(self.request, '¡Bienvenido! Te has registrado exitosamente.')
        return response

TiendaSaludable/productos/templates/productos/carrito.html
{% extends 'productos/html_base.html' %}

{% block content %}
    <!-- Encabezado de la página -->
    <h1>Carrito de Compras</h1>

    {% if not user.is_authenticated %}
    <p>Debes iniciar sesión para poder visualizar los artículos agregados a tu carrito de compras</p>
    {% endif %}

    <!-- Verifica si hay elementos en el carrito -->
    {% if carrito %}
        <!-- Tabla para mostrar los detalles de los productos en el carrito -->
        <table>
            <thead>
                <tr>
                    <th>Producto</th>
                    <th>Precio</th>
                    <th>Cantidad</th>
                    <th>Subtotal</th>
                    <th>Eliminar</th>
                </tr>
            </thead>
            <tbody>
                <!-- Bucle para recorrer cada elemento en el carrito -->
                {% for item in carrito %}
                    <tr>
                        <!-- Muestra información del producto en cada fila -->
                        <td>{{ item.producto.nombre }}</td>
                        <td>${{ item.producto.precio }}</td>
                        <td>{{ item.cantidad }}</td>
                        <td>${{ item.subtotal }}</td>
                        <td>
                            <!-- Formulario para eliminar el elemento del carrito -->
                            <form method="post" action="{% url 'eliminar_del_carrito' item.id %}">
                                {% csrf_token %}
                                <input type="submit" value="Eliminar">
                            </form>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <!-- Muestra el total del carrito -->
        <p>Total: ${{ total_carrito }}</p>
    {% else %}
        <!-- Mensaje si el carrito está vacío -->
        <p>El carrito está vacío.</p>
    {% endif %}
{% endblock %}

TiendaSaludable/productos/templates/productos/contacto.html
{% extends 'productos/html_base.html' %}

{% block title %}Tienda Saludable - Contacto{% endblock %}

{% block content %}
    <!-- Encabezado de la página -->
    <h1>Contacto</h1>
    
    <!-- Formulario de contacto con método POST y acción correspondiente a la vista de contacto -->
    <form method="post" action="{% url 'productos:contacto' %}">
        {% csrf_token %} <!-- Token CSRF para protección contra ataques CSRF -->
        
        <!-- Renderiza el formulario como párrafos -->
        {{ form.as_p }}
        
        <!-- Botón de envío del formulario -->
        <button type="submit">Enviar</button>
    </form>
{% endblock %}

TiendaSaludable/productos/templates/productos/home.html
{% extends 'productos/html_base.html' %}

{% block title %}Tienda Saludable - Home{% endblock %}

{% block content %}
    <!-- Encabezado principal de la página -->
    <h1>Bienvenido a Tienda Saludable</h1>
    
    <!-- Párrafo introductorio sobre la historia y la misión de la tienda -->
    <p>
        En el corazón de nuestra historia está la pasión por ofrecer opciones de vida más saludables y deliciosas. Comenzamos como una pequeña tienda local con la visión de proporcionar productos de alta calidad que promuevan el bienestar y la alimentación consciente.
    </p>

    
    <p>
        A lo largo de los años, hemos crecido y evolucionado, convirtiéndonos en un destino confiable para aquellos que buscan una variedad de opciones nutricionales. Nuestra dedicación se refleja en la cuidadosa selección de alimentos orgánicos, snacks saludables y suplementos nutricionales que ofrecemos. En Tienda Saludable, no solo ofrecemos productos, sino también una experiencia de compra que inspira y educa.
    </p>

    
    <p>
        Creemos en el poder de las decisiones informadas sobre la nutrición y en el impacto positivo que estas decisiones pueden tener en la vida cotidiana. Queremos ser más que una tienda; aspiramos a ser tu guía en el viaje hacia un estilo de vida más saludable. Nuestro compromiso va más allá de vender productos; buscamos ser una fuente de inspiración para adoptar un enfoque consciente hacia la alimentación.
    </p>

    
    <p>
        Únete a nosotros en la revolución de la alimentación consciente. Explora nuestras estanterías virtuales, sumérgete en la diversidad de opciones y descubre cómo cada elección que haces puede contribuir a tu bienestar general. En Tienda Saludable, estamos comprometidos con tu salud y felicidad. ¡Bienvenido a una nueva forma de disfrutar de la vida a través de la nutrición!
    </p>
{% endblock %}

TiendaSaludable/productos/templates/productos/html_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Configuración básica del documento -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <!-- Título de la página, se puede personalizar en las plantillas que extienden esta base -->
    <title>{% block title %}Tienda Saludable{% endblock %}</title>
    
    <!-- Enlace al archivo CSS local -->
    <link rel="stylesheet" href="{% static 'productos/css/styles.css' %}">
    
    <!-- Enlace al archivo CSS de Bootstrap desde un CDN -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    
    <!-- Estilo adicional para el fondo del body -->
    <style>
        body {
            background-color: rgb(210, 243, 207);
        }
    </style>
</head>
<body>
    <!-- Barra de navegación -->
    <ul class="nav justify-content-center">
        <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'productos:home' %}">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'productos:lista_articulos' %}">Artículos</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'productos:carrito' %}">Carrito</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'productos:contacto' %}">Contacto</a>
        </li>
        {% if user.is_authenticated %}
            <li class="nav-item">
                <form method="post" action="{% url 'productos:logout' %}">
                    {% csrf_token %}
                    <button type="submit" class="nav-link" style="background: none; border: none; cursor: pointer;">Logout</button>
                </form>
            </li>
        {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'productos:login' %}">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'productos:registro' %}">Registro</a>
            </li>
        {% endif %}
    </ul>
    
    <!-- Contenido principal de la página -->
    <div id="content">
        {% block content %}{% endblock %}
    </div>
    
    <!-- Inclusión del script de Bootstrap desde un CDN -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

TiendaSaludable/productos/templates/productos/lista_articulos.html
{% extends 'productos/html_base.html' %}

{% block content %}
  <!-- Encabezado de la página -->
  <h1>Lista de Artículos</h1>
  
  <!-- Lista de artículos utilizando un bucle for -->
  <ul>
    {% for articulo in articulos %}
      <li>
        <!-- Detalles del artículo -->
        <strong>{{ articulo.nombre }}</strong><br>
        Descripción: {{ articulo.descripcion }}<br>
        Precio: ${{ articulo.precio }}<br>
        Categoria: {{ articulo.categoria }}<br>
        Stock: {{ articulo.disponible }}<br>
        
        <!-- Formulario para agregar el artículo al carrito -->
        <form method="post" action="{% url 'productos:agregar_al_carrito' articulo.id %}">
          {% csrf_token %}
          <input type="submit" value="Agregar al carrito">
        </form>
        
        {% if not user.is_authenticated %}
          <!-- Mensaje si el usuario no ha iniciado sesión -->
          <p>Debes iniciar sesión para agregar artículos al carrito.</p>
        {% endif %}
      </li>
    {% endfor %}
  </ul>
{% endblock %}

TiendaSaludable/productos/templates/productos/login.html
<!--productos/templates/productos/login.html -->
{% extends 'productos/html_base.html' %}

{% block title %}Iniciar Sesión{% endblock %}

{% block content %}
    <h2>Iniciar Sesión</h2>
    <form method="post" action="{% url 'productos:login' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Iniciar Sesión</button>
    </form>
{% endblock %}

TiendaSaludable/productos/templates/productos/logout.html
<!-- productos/templates/productos/logout.html -->

<div id="logoutModal" class="modal">
    <div class="modal-content">
      <h2>Cerrar Sesión</h2>
      <form method="post" action="{% url 'logout' %}">
        {% csrf_token %}
        <button type="submit">Cerrar sesión</button>
      </form>
      <button id="cancelLogout">Cancelar</button>
    </div>
</div>

TiendaSaludable/productos/templates/productos/registro.html
<!-- registro.html -->

{% extends 'productos/html_base.html' %}

{% block content %}
  <h2>Registro de Usuario</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Registrarse</button>
  </form>
{% endblock %}